### ISSUE TITLE
Move back the NSE code/config to the original Element folder

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#411]
We created previously 2 targets TchapNSE and BtchapNSE based on the Element RiotNSE target

We want here to ease the rebase by moving back the NSE code to the original folder, and limit the Tchap target to the minimum

During this task, we should add the LocalAuthenticationService code in the Tchap-iOS project by disabling/hiding the service for the moment

**Comment by phlniji** [comment]
@giomfo With the latest commit on this branch, I added a pod install command at the end of the project generation (with xcodegen). But I added the arch argument to force CocoaPods to use the x86_64 binary (due to some CocoaPods incompatibilities with Apple Silicon based Macs).
So, if you have any issue with this on an Intel based Mac, I should remove this post generate script.
