### ISSUE TITLE
update the SDK version

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#431]
Following the Rebase onto vector-im/element-ios 1.6.8 #430, we will update the matrix-ios-sdk version

We are using currently the branch [dinum_dev](https://github.com/matrix-org/matrix-ios-sdk/tree/dinum_dev). This branch provides us the following [commit](https://github.com/matrix-org/matrix-ios-sdk/commit/8879044cd2eb6527a92b330b76f3a235104cc905):  "MXStore: Add new API to remove expired messages, Commit: 8879044cd2eb6527a92b330b76f3a235104cc905 [8879044c] - 11 August 2021 at 22:25:55 CEST
This commit is related to the room retention feature enabled only in Btchap for testing. The changes (like the new event type "@m.room.retention") are not available in matrix-ios-sdk FOSS

Until we implement the support of the room retention at the sdk level (FOSS), we decided to create at each Tchap-ios rebase a specific branch of matrix-ios-sdk based on the most recent tagged sdk, and apply a patch related to this commit  [8879044c]. The new branch will be named "dinum_vx.y.z" where vx.y.z will be the sdk tag. The previous branch may be removed when it can be easily created again

**Comment by phlniji** [comment]
Here is the git patch to apply :
[patch.diff.txt](https://github.com/tchapgouv/tchap-ios/files/7717935/patch.diff.txt)

/!\ Because of GitHub file types restrictions, don't forget to remove the txt extension after you downloaded it. /!\

To check if there will be no error when applying the patch, try this :
`git apply --check patch.diff`

And if everything is ok, you can apply the patch :
`git apply patch.diff`


I also made a local branch (dinum_v0.20.15) to test it with success.
