### ISSUE TITLE
The TAC are not displayed

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#525]
click on the TAC from Tchap settings is stuck on a blank screen

**Comment by phlniji** [comment]
There is an issue with the certificate at the URL given for TAC.
We currently have this URL to access the TAC : https://www.tchap.gouv.fr/tac.html
But It is not signed with the same root certificate as the others (ie: https://tchap.beta.gouv.fr/faq ). It seems to be a Let's Encrypt one, instead of the Certigna one.
So the certificate pinning blocked the access to the TAC URL.

**Comment by jdauphant** [comment]
I didn't had this problem in v1.2, so certificat pinning was introduced in the new version ?

**Comment by phlniji** [comment]
The certificate pinning mechanism has been improved for WebViews in Element code since Tchap v1.2.

**Comment by giomfo** [comment]
> I didn't had this problem in v1.2, so certificat pinning was introduced in the new version ?

Do you test recently in v1.2 since the new CGU url has been published?
https://www.tchap.gouv.fr/tac.html  is redirected to https://tchap.beta.gouv.fr/cgu now

**Comment by jdauphant** [comment]
> > I didn't had this problem in v1.2, so certificat pinning was introduced in the new version ?
> 
> Do you test recently in v1.2 since the new CGU url has been published? https://www.tchap.gouv.fr/tac.html is redirected to https://tchap.beta.gouv.fr/cgu now

Yes I have tested it.
I will order the good certificat for tchap.beta.gouv.fr

**Comment by giomfo** [comment]
waiting for the right certificate for tchap.beta.gouv.fr to unblock this issue

**Comment by jdauphant** [comment]
@giomfo @phlniji can you confirm the problem is solved ?

**Comment by giomfo** [comment]
fixed
