### ISSUE TITLE
[AppLayout] Manage Invited users restrictions

### ISSUE THREAD

**Issue by phlniji** [tchapgouv/tchap-ios#701]
With the new AppLayout, an invited user can try to do these things, but should not :
- Create a room
- Invite a user

We should fix this.

**Comment by giomfo** [comment]
I reopen this issue because we missed one point, invited user (external user) could not search/access forums.
So this option must be hidden too
<img width="348" alt="image" src="https://user-images.githubusercontent.com/8969772/210796319-7f5f9d73-ae12-4418-9888-67dec3d9182c.png">

The plus icon should be hidden in case of invited user. This is not useful to hide each action separately
