### ISSUE TITLE
Update French translations in Tchap

### ISSUE THREAD

**Issue by yostyle** [tchapgouv/tchap-ios#747]
Some strings has been updated in [Element](https://github.com/tchapgouv/tchap-ios/issues/727). Following strings need to be updated in tchap only.

Quoi | Element | Tchap
-- | -- | --
Conversation many-to-many privé | Salon privé | Salon
Conversation many-to-many publique | Salon public | Forum
Clé de déchiffrement d’une session | Clés de déchiffrement | Clés Tchap
Backup de tous les messages chiffrés dans le cloud | Sauvegarde sécurisée | Sauvegarde automatique des messages
Email  | Email | Adresse mail  
Session | Session | Appareil

**Comment by NicolasBuquet** [comment]
Some Strings have no equivalent between fr and en : 
- create_room_section_footer_type (fr)
- create_room_section_footer_type_private (en)
- create_room_section_footer_type_restricted (en)
- create_room_section_footer_type_public (en)

Need careful review for `Clés de déchiffrement`replacement because it was npt present as such in source code. Replacement occured for `Clés de chiffrement`and `encryption keys`.

**Comment by giomfo** [comment]
@NicolasBuquet one more change is requested on Tchap side:

Quoi | Element | Tchap
-- | -- | --
Accès annuaire des conv. many-to-many publiques | Parcourir les salons/Parcourir les salons publics | Rejoindre un forum
-- | -- | --

**Comment by giomfo** [comment]
> Some Strings have no equivalent between fr and en :

@yostyle Can you please have a look in Element-iOS strings

**Comment by NicolasBuquet** [comment]
Done,
Note that I found `Parcourir les salons` string, but no `Parcourir les salons publics` string.
